# Numpy Basic Operations:-

Types Of Numpy Array:-

1.Scalar [Zero Dimension Array]

2.Vector [1 Dimension Array]

3.Matrix [2 Dimension Array]

4.Multidimension [3 Dimension Array]

In [ ]:
import numpy as np

In [ ]:
# Scalar
arr=np.array(10)
arr


In [ ]:
arr.ndim # N-Dimensional use for find out dimension of Numpy Array

In [ ]:
# Vector Numpy Array
arr=np.array([2,3,4,5,6,7,8])
arr

In [ ]:
arr.ndim

In [ ]:
np.__version__

In [ ]:
arr

In [ ]:
type(arr)

In [ ]:
arr.size

In [ ]:
arr.dtype

In [ ]:
arr.itemsize

In [ ]:
arr.shape

(row,column)

In [ ]:
arr=np.array([2,3,4,5,6,7,8,9],dtype=np.int32) # to minimize memory to 32 byte
arr

In [ ]:
arr.dtype

In [ ]:
arr.itemsize

In [ ]:
arr=np.array([2,3,4,5,6,7,8,9],dtype=np.int16) # to minimize memory to 32 byte
arr

In [ ]:
arr.dtype

In [ ]:
arr.itemsize

In [ ]:
arr=np.array([2,3,4,5,6,7,8,9],dtype=np.float32) # to minimize memory to 32 byte
arr

In [ ]:
arr.dtype

In [ ]:
arr.itemsize

In [ ]:

arr=np.array([2,3,4.3,5.0])
arr

In [ ]:
arr=np.array([2,3,4.5,5.0])
arr

will make all float since takes similar data

In [ ]:
arr=np.array([10,10.20,'a'])
arr

In [ ]:
arr.itemsize

will make all string

In [ ]:
np.zeros(10)

bydefault take float

In [ ]:
np.zeros(10,dtype=int)

In [ ]:
np.ones(5)

In [ ]:
np.ones(5,dtype=int)

In [ ]:
np.full(10,5)

display 10 time 5

In [ ]:
np.full(10,5,dtype=float)

# Two Dimensional Array

In [ ]:
arr=np.array([[2,4],[5,6],[7,8]])
arr #3 x 2 Matrix


In [ ]:
arr.shape

row-sample

column-feature

In [ ]:
arr.ndim

In [ ]:
arr.dtype

In [ ]:
arr.size

In [ ]:
arr=np.array([[2,3,4],[5,6,7],[8,9,1]],dtype=np.int32)
arr

In [ ]:
arr.shape

In [ ]:
arr[1,1]


In [ ]:
print(arr[::-1,::-1])

reverses column and rows

In [ ]:
print(arr[2,::-2])

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((3,3),dtype=int)

In [ ]:
# Sparse Matrix

In [ ]:
np.ones((2,3))

In [ ]:
np.ones((2,3),dtype=int)

In [ ]:
np.full((2,3),2)


In [ ]:
np.full((2,3),2,dtype=float)

In [ ]:
np.empty((4,4))

takes random value

In [ ]:
np.empty((2,3))

In [ ]:
np.linspace(1,5)

divides num from 1 to 5 in 50 equal parts by default

In [ ]:
np.linspace(1,5,num=10,retstep=True)

divides in 10 equal parts as given and gives diff between each by retstep

In [ ]:
np.linspace(1,5,num=10,retstep=True,endpoint=False)

here will not take last point that is 5 so diff will also be different as a result 

# Diff bw range() and arange():

In [ ]:
arr=np.arange(10)
arr


In [ ]:
arr.dtype

In [ ]:
arr=np.arange(1,21)
arr

In [ ]:
arr=np.arange(1,21,3,dtype=float)
arr

# Diff bww reshape() & resize()

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[2,3],[4,5],[6,7]])
arr

In [ ]:
arr.reshape(1,6)

In [ ]:
arr.reshape(2,3)

In [ ]:
arr # temp change

In [ ]:
arr.resize(2,3)

In [ ]:
arr # permanent change

# Diff bw ravel() & flatten() method in numpy array

2D array into 1D array

In [ ]:
arr

In [ ]:
arr.ndim

In [ ]:
arr.ravel()

In [ ]:
arr.ndim

In [ ]:
arr

In [ ]:
a=arr.ravel()

In [ ]:
a

In [ ]:
arr

In [ ]:
arr.flatten()

In [ ]:
b=arr.flatten()
b

In [ ]:
a

In [ ]:
a[3]=9

In [ ]:
a

In [ ]:
arr

modifies element in actual array also but not with flatten

In [ ]:
b

In [ ]:
b[5]=12
b

In [ ]:
arr

no change in  actual arr

# Mathematical Operations in Numpy Array:- 

In [ ]:
arr=np.array([[2,6,5],[9,8,1],[6,4,7]])
arr # 3x3

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis=0)# colmn wise sum

In [ ]:
arr.sum(axis=1) # row wise sum

In [ ]:
arr.min()

In [ ]:
arr.min(axis=0) # column wise min

In [ ]:
arr.min(axis=1) # row wise min

In [ ]:
arr.max()

In [ ]:
arr.max(axis=0)

In [ ]:
arr.max(axis=1) # func

In [ ]:
np.square(arr) # method

In [ ]:
np.sqrt(arr)

In [ ]:
np.log(arr) # log2 base

# Stacking of Numpy Array:-

In [ ]:
a=np.arange(6).reshape(3,2)
a

In [ ]:
b=np.arange(6,12).reshape(3,2)
b

In [ ]:
np.vstack((a,b)) # vertically merges both a and b arrays

In [ ]:
np.hstack((a,b)) # horzontally merges 

# Splitting of Numpy Array

In [ ]:
arr=np.arange(30).reshape(2,15)
arr

In [ ]:
np.hsplit(arr,3)

In [ ]:
np.hsplit(arr,5)

splits in equal parts

In [ ]:
result=np.hsplit(arr,3)

In [ ]:
result[0]

In [ ]:
result[1]

In [ ]:
result[2]

In [ ]:
result

In [ ]:
np.vsplit(arr,2) 

# Indexing with Boolean Array:-

In [ ]:
a=np.arange(12).reshape(4,3)
a

In [ ]:
b=a>4
b

In [ ]:
a[b] # display all true values

In [ ]:
a[b]=-1 # need not to do -1 one by one

In [ ]:
a

In [ ]:
a=np.arange(6).reshape(3,2)
a

In [ ]:
b=np.arange(6,12).reshape(3,2)
b

In [ ]:
np.concatenate((a,b),axis=0) # colmn wise merge like hstack

In [ ]:
np.concatenate((a,b),axis=1)# row wise merge like vstack

# Random Numbers in Numpy Array

In [ ]:
np.random.randint(2,10,size=(3,4))

In [ ]:
np.random.randint(2,10,size=(3,4))

In [ ]:
np.random.rand(4,2) #  btw 0.0 & 1.0

# Transpose of Numpy Array:-

In [ ]:
a=np.array([[2,3],[7,8],[4,5]])
a

In [ ]:
a.transpose()

# Sorting of Numpy Array

In [ ]:
arr=np.array([[3,1,8],[9,5,2],[6,4,9],[4,7,2]])
arr

In [ ]:
arr.sort() # bydefault quicksort(faster) and axis=-1
arr

In [ ]:
arr.sort(axis=1) #row wise asc order

In [ ]:
arr

In [ ]:
arr.sort(axis=0) # colmn wise asc order
arr

 .argmax() & .argmin()

In [ ]:
arr=np.array([[2,3],[6,4],[7,8],[9,1]])
arr

In [ ]:
np.argmax(arr)# displays max element index

In [ ]:
np.argmin(arr) # displays min element index

In [ ]:
np.argmax(arr,axis=0) #colmn wise max element index

# How to Convert 2D Numpy Array To List:-

In [ ]:
arr=np.array([[2,3,4],[5,6,7],[7,8,9]])
arr

In [ ]:
arr.ndim

In [ ]:
arr.tolist() # converted 2D into nested list

Lets convert to single list

In [ ]:
b=arr.flatten()
b

In [ ]:
b.ndim

In [ ]:
li=b.tolist() # Converted 1D into Single list
li

In [ ]:
type(li)

In [3]:
import numpy as np

In [5]:
arr=np.array([[2,3],[4,5],[6,7]])
arr

array([[2, 3],
       [4, 5],
       [6, 7]])

In [7]:
arr.dtype

dtype('int64')

In [9]:
arr=arr.astype('float')
arr

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [11]:
arr.dtype

dtype('float64')

In [13]:
arr

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [15]:
arr=arr.astype('int')

In [17]:
arr

array([[2, 3],
       [4, 5],
       [6, 7]])

# How To Add New Column/Row in 2D Numpy Array:

In [20]:
np.insert(arr,1,[8,2,1],axis=1)# colmn wise where 1 is index

array([[2, 8, 3],
       [4, 2, 5],
       [6, 1, 7]])

In [24]:
arr

array([[2, 3],
       [4, 5],
       [6, 7]])

In [28]:
np.insert(arr,2,[8],axis=1)

array([[2, 3, 8],
       [4, 5, 8],
       [6, 7, 8]])

In [32]:
np.insert(arr,1,[8,1],axis=0) # row wise 

array([[2, 3],
       [8, 1],
       [4, 5],
       [6, 7]])

In [36]:
np.insert(arr,2,[1],axis=0)

array([[2, 3],
       [4, 5],
       [1, 1],
       [6, 7]])

# How To Delete Row/Column in a 2D Numpy Array

In [39]:
np.delete(arr,1,axis=1)

array([[2],
       [4],
       [6]])

In [41]:
np.delete(arr,1,0)

array([[2, 3],
       [6, 7]])

# How To Convert List and Tuple into Numpy Array

In [44]:
data=[[2,3],[4,5],[6,7],[8,9]]
data

[[2, 3], [4, 5], [6, 7], [8, 9]]

In [46]:
type(data)

list

In [48]:
np.asarray(data)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
type(arr)

numpy.ndarray

In [52]:
arr.ndim

2

In [56]:
data=([2,3,4],[5,6,7],[8,9,1])
data

([2, 3, 4], [5, 6, 7], [8, 9, 1])

In [58]:
type(data)

tuple

In [62]:
np.asarray(data)

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [64]:
type(arr)

numpy.ndarray

# MULTI - DIMENSIONAL ARRAY:-

In [68]:
arr=np.arange(90)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [70]:
arr.reshape(9,2,5)# multiplication must be 90
#(group,row,column)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [72]:
arr=np.arange(90).reshape(9,2,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [74]:
arr.ndim

3

In [76]:
arr.shape

(9, 2, 5)

In [78]:
arr.dtype

dtype('int64')

In [80]:
arr[0][1][2:0:-1]

array([7, 6])

In [82]:
arr[0][1][2:9:-1]

array([], dtype=int64)

In [84]:
arr=np.array([[[2,3,4],[5,6,7],[8,9,1]]])

In [86]:
arr

array([[[2, 3, 4],
        [5, 6, 7],
        [8, 9, 1]]])

In [88]:
arr.shape

(1, 3, 3)

In [90]:
arr.ndim

3